/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

/*
 * NOTICE: Do not edit this file manually.
 * This file is automatically generated by the OpenAPI Generator, @kbn/openapi-generator.
 *
 * info:
 *   title: Watchlist CSV Upload Schema
 *   version: 2023-10-31
 */

import { z } from '@kbn/zod/v4';

export type WatchlistCsvUploadResponseItem = z.infer<typeof WatchlistCsvUploadResponseItem>;
export const WatchlistCsvUploadResponseItem = z.object({
  status: z.enum(['success', 'failure', 'unmatched']),
  matchedEntities: z.number().int(),
  error: z.string().optional(),
});

export type UploadWatchlistCsvRequestParams = z.infer<typeof UploadWatchlistCsvRequestParams>;
export const UploadWatchlistCsvRequestParams = z.object({
  /**
   * The ID of the watchlist to add entities to
   */
  watchlist_id: z.string(),
});
export type UploadWatchlistCsvRequestParamsInput = z.input<typeof UploadWatchlistCsvRequestParams>;

export type UploadWatchlistCsvResponse = z.infer<typeof UploadWatchlistCsvResponse>;
export const UploadWatchlistCsvResponse = z.object({
  successful: z.number().int(),
  failed: z.number().int(),
  total: z.number().int(),
  unmatched: z.number().int(),
  items: z.array(WatchlistCsvUploadResponseItem),
});
