on:
  issue_comment:
    types:
      - created

jobs:
  issue_commented:
    name: sync ci checks on comment
    if: |
      github.event.issue.pull_request
      && contains(fromJSON('["OWNER","MEMBER","COLLABORATOR"]'), github.event.comment.author_association)
      && startsWith(github.event.comment.body, '/sync-ci')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kibana-operations
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          repository: 'elastic/kibana-operations'
          ref: main
          path: ./kibana-operations
          token: ${{secrets.KIBANAMACHINE_TOKEN}}
          persist-credentials: false

      - name: Sync CI Status Checks
        working-directory: ./kibana-operations/triage
        env:
          GITHUB_TOKEN: ${{secrets.KIBANAMACHINE_TOKEN}}
          BUILDKITE_TOKEN: ${{secrets.OPS_BUILDKITE_TOKEN}}
        run: |
          npm ci --omit=dev
          node verify-ci-check ${{github.event.issue.number}}
